apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: jimtestdockenv/database_service_project:latest
          ports:
            - containerPort: 5000
          

---

apiVersion: v1
kind: Service
metadata:
  name: boardgame
spec:
  type: NodePort
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30000