name: build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      
      - name: Build with Maven
        run: mvn -B clean verify

      - name: Run tests
        run: mvn test
      
      # - name: SonarQube Analysis
      #   uses: sonarsource/sonarqube-scan-action@v2
      #   with:
      #     projectBaseDir: .
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONARCUBE_SERVER }}
      #     SONAR_HOST_URL: https://epencephalic-wilber-multiovulated.ngrok-free.dev

      # - name: SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@v1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONARCUBE_SERVER }}
      #     SONAR_HOST_URL: https://epencephalic-wilber-multiovulated.ngrok-free.dev

    

      - name: Deploy to Nexus Repository
        run: mvn deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}



