name: build and test

on: [push]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11 for x64
        uses : actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      
      - name: build with maven
        run: mvn -B clean verify

      - name: run tests
        run: mvn test
      
      - name: SonarQube_analysis
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
           SONAR_TOKEN: ${{secrets.SONARCUBE_SERVER}}
           SONAR_HOST_URL: http://192.168.0.118:9000

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1

        env:
           SONAR_TOKEN: ${{secrets.SONARCUBE_SERVER}}
           SONAR_HOST_URL: http://192.168.0.118:9000
